### PR TITLE
Improved RSI calculation and configuration.

### PR DESCRIPTION
**Pull request by Lokraan**
## Changes
- Improved RSI Calculation. (More readable, efficient, and accurate: Matches Bittrex RSI Calculations) .
- get_closing_prices in strategy_utils.py is now one line (ish)
- Loading config is now in a separate method. 
- Provides customizable update interval in config file.

### CODE REVIEW

**Comment by Lokraan** [comment]
I saw that you guys are already creating a new method for configuration.

If needed I can rollback the configuration changes and make the RSI changes the only ones remaining.

**Comment by AbenezerMamo** [comment]
Thanks for the improvements! Though before we proceed, see if you can replace the "i" in the loops to be more descriptive of what's being iterated through that'd be dope!

I'll let @shads2 decide how he wants to proceed with this PR

**Comment by shads2** [comment]
Hey @Lokraan I'll merge these improvements into the config update change :+1: 

The only part that may not work is

> period_count=1000, time_unit='1h'

Which is going to try and fetch 1000, 1 hour blocks... historical data on the majority of exchanges won't go back that far.

**Comment by Lokraan** [comment]
@shads2 My only goal is to get as much data as possible for RSI calculations because Bittrex uses all available data to calculate the RSI. From what I can tell (as far as Bittrex) if the period_count is greater than how much data they have, the just return all of it.

**Comment by Lokraan** [comment]
Closed by fe59e22

**Pull request closed without merging**
